/* FlashGrocer – products-data.js */
'use strict';

const ALL_PRODUCTS = [
  {
    id: 1,
    name: "Fresh Red Apples (1kg)",
    category: "grocery",
    price: 89,
    originalPrice: 120,
    rating: 4.8,
    reviews: 342,
    badge: "Fresh",
    img: "images/cat_grocery.png",
    delivery: "In 10 min"
  },
  {
    id: 2,
    name: "Full Cream Milk (1L)",
    category: "grocery",
    price: 64,
    originalPrice: 75,
    rating: 4.6,
    reviews: 210,
    badge: "Daily",
    img: "images/prod_milk.png",
    delivery: "In 10 min"
  },
  {
    id: 3,
    name: "Whole Wheat Bread",
    category: "grocery",
    price: 45,
    originalPrice: 55,
    rating: 4.5,
    reviews: 190,
    badge: "Fresh",
    img: "images/prod_bread.png",
    delivery: "In 10 min"
  },
  {
    id: 4,
    name: "Organic Bananas (Dozen)",
    category: "grocery",
    price: 59,
    originalPrice: 70,
    rating: 4.7,
    reviews: 280,
    badge: "Organic",
    img: "images/cat_grocery.png",
    delivery: "In 10 min"
  },
  {
    id: 101,
    name: "Aashirvaad Atta (5kg)",
    category: "grocery",
    price: 239,
    originalPrice: 280,
    rating: 4.7,
    reviews: 520,
    badge: "Top Seller",
    img: "images/cat_grocery.png",
    delivery: "In 15 min"
  },
  {
    id: 102,
    name: "India Gate Basmati Rice (5kg)",
    category: "grocery",
    price: 499,
    originalPrice: 599,
    rating: 4.8,
    reviews: 410,
    badge: "Premium",
    img: "images/cat_grocery.png",
    delivery: "In 15 min"
  },
  {
    id: 103,
    name: "Toor Dal (1kg)",
    category: "grocery",
    price: 149,
    originalPrice: 180,
    rating: 4.5,
    reviews: 240,
    badge: "Fresh",
    img: "images/cat_grocery.png",
    delivery: "In 15 min"
  },
  {
    id: 104,
    name: "Fortune Sunflower Oil (1L)",
    category: "grocery",
    price: 149,
    originalPrice: 170,
    rating: 4.6,
    reviews: 320,
    badge: "Pure",
    img: "images/cat_grocery.png",
    delivery: "In 15 min"
  },
  {
    id: 105,
    name: "Amul Butter (500g)",
    category: "grocery",
    price: 265,
    originalPrice: 290,
    rating: 4.9,
    reviews: 680,
    badge: "Loved",
    img: "images/cat_grocery.png",
    delivery: "In 10 min"
  },
  {
    id: 106,
    name: "Chana Dal (1kg)",
    category: "grocery",
    price: 129,
    originalPrice: 160,
    rating: 4.4,
    reviews: 180,
    badge: "Fresh",
    img: "images/cat_grocery.png",
    delivery: "In 15 min"
  },
  {
    id: 107,
    name: "Tomatoes (1kg)",
    category: "grocery",
    price: 39,
    originalPrice: 60,
    rating: 4.5,
    reviews: 290,
    badge: "Fresh",
    img: "images/cat_grocery.png",
    delivery: "In 10 min"
  },
  {
    id: 108,
    name: "Onions (1kg)",
    category: "grocery",
    price: 35,
    originalPrice: 50,
    rating: 4.3,
    reviews: 210,
    badge: "Fresh",
    img: "images/cat_grocery.png",
    delivery: "In 10 min"
  },
  {
    id: 10,
    name: "Margherita Pizza (12\")",
    category: "food",
    price: 249,
    originalPrice: 299,
    rating: 4.8,
    reviews: 450,
    badge: "Popular",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 11,
    name: "Chicken Burger Combo",
    category: "food",
    price: 179,
    originalPrice: 219,
    rating: 4.7,
    reviews: 380,
    badge: "Hot",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 1401,
    name: "Hyderabadi Biryani (2 Serves)",
    category: "food",
    price: 349,
    originalPrice: 399,
    rating: 4.9,
    reviews: 1200,
    badge: "Authentic",
    img: "images/cat_food.png",
    delivery: "In 30 min"
  },
  {
    id: 1402,
    name: "Masala Dosa with Sambar",
    category: "food",
    price: 89,
    originalPrice: 119,
    rating: 4.8,
    reviews: 820,
    badge: "South",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 1403,
    name: "Butter Chicken + Naan (2 pc)",
    category: "food",
    price: 299,
    originalPrice: 349,
    rating: 4.8,
    reviews: 960,
    badge: "🔥 Hot",
    img: "images/cat_food.png",
    delivery: "In 30 min"
  },
  {
    id: 1404,
    name: "Pav Bhaji Plate",
    category: "food",
    price: 99,
    originalPrice: 139,
    rating: 4.7,
    reviews: 680,
    badge: "Street",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 1405,
    name: "Idli Sambar Combo (6 pcs)",
    category: "food",
    price: 69,
    originalPrice: 99,
    rating: 4.6,
    reviews: 540,
    badge: "Healthy",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 1501,
    name: "Amul Tricone Ice Cream (4 pc)",
    category: "icecream",
    price: 99,
    originalPrice: 140,
    rating: 4.8,
    reviews: 2100,
    badge: "🍦 Amul",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 1502,
    name: "Baskin Robbins Tub (500ml)",
    category: "icecream",
    price: 299,
    originalPrice: 350,
    rating: 4.9,
    reviews: 1400,
    badge: "Premium",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 1503,
    name: "Kwality Wall's Cornetto 4-Pack",
    category: "icecream",
    price: 199,
    originalPrice: 260,
    rating: 4.7,
    reviews: 920,
    badge: "Crunchy",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 1504,
    name: "Frozen Mango Kulfi (6 sticks)",
    category: "icecream",
    price: 149,
    originalPrice: 199,
    rating: 4.8,
    reviews: 760,
    badge: "Desi",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 1601,
    name: "Coca-Cola 2L PET Bottle",
    category: "drinks",
    price: 89,
    originalPrice: 105,
    rating: 4.7,
    reviews: 3200,
    badge: "Refresh",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 1602,
    name: "Paper Boat Litchi Juice (200ml×6)",
    category: "drinks",
    price: 99,
    originalPrice: 140,
    rating: 4.8,
    reviews: 1800,
    badge: "Natural",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 1603,
    name: "Red Bull Energy Drink (250ml)",
    category: "drinks",
    price: 125,
    originalPrice: 150,
    rating: 4.6,
    reviews: 2100,
    badge: "Energy",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 1604,
    name: "Tropicana Orange 1L",
    category: "drinks",
    price: 99,
    originalPrice: 130,
    rating: 4.6,
    reviews: 980,
    badge: "Vitamin C",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 1701,
    name: "Lay's Classic Salted (Pack 5)",
    category: "snacks",
    price: 99,
    originalPrice: 130,
    rating: 4.7,
    reviews: 2800,
    badge: "Crispy",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 1702,
    name: "Oreo Cream Biscuits (Pack 3)",
    category: "snacks",
    price: 79,
    originalPrice: 99,
    rating: 4.8,
    reviews: 3400,
    badge: "Classic",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 1703,
    name: "Paan (Meetha Paan x5)",
    category: "snacks",
    price: 99,
    originalPrice: 120,
    rating: 4.5,
    reviews: 640,
    badge: "Fresh",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 1704,
    name: "Kaju Katli Box (250g)",
    category: "snacks",
    price: 299,
    originalPrice: 399,
    rating: 4.9,
    reviews: 1800,
    badge: "Sweet",
    img: "images/cat_food.png",
    delivery: "In 30 min"
  },
  {
    id: 3001,
    name: "Chicken Dum Biryani (Family Pack)",
    category: "food",
    price: 699,
    originalPrice: 899,
    rating: 4.9,
    reviews: 2500,
    badge: "Bestseller",
    img: "images/cat_food.png",
    delivery: "In 30 min"
  },
  {
    id: 3002,
    name: "Mutton Biryani (Special)",
    category: "food",
    price: 499,
    originalPrice: 599,
    rating: 4.8,
    reviews: 1800,
    badge: "Premium",
    img: "images/cat_food.png",
    delivery: "In 30 min"
  },
  {
    id: 3003,
    name: "Chicken 65 (Starter)",
    category: "food",
    price: 249,
    originalPrice: 299,
    rating: 4.7,
    reviews: 1200,
    badge: "Spicy",
    img: "images/cat_food.png",
    delivery: "In 20 min"
  },
  {
    id: 3004,
    name: "Tandoori Chicken (Half)",
    category: "food",
    price: 349,
    originalPrice: 450,
    rating: 4.8,
    reviews: 1500,
    badge: "Hot",
    img: "images/cat_food.png",
    delivery: "In 25 min"
  },
  {
    id: 3005,
    name: "Chicken Tikka Masala",
    category: "food",
    price: 299,
    originalPrice: 399,
    rating: 4.6,
    reviews: 900,
    badge: "Must Try",
    img: "images/cat_food.png",
    delivery: "In 25 min"
  },
  {
    id: 3006,
    name: "Egg Biryani",
    category: "food",
    price: 229,
    originalPrice: 279,
    rating: 4.5,
    reviews: 600,
    badge: "Tasty",
    img: "images/cat_food.png",
    delivery: "In 30 min"
  },
  {
    id: 3007,
    name: "Paradise Special Biryani",
    category: "food",
    price: 399,
    originalPrice: 499,
    rating: 4.9,
    reviews: 3500,
    badge: "Iconic",
    img: "images/cat_food.png",
    delivery: "In 30 min"
  },
  {
    id: 3008,
    name: "Chicken Lollipop (6 pcs)",
    category: "food",
    price: 279,
    originalPrice: 329,
    rating: 4.7,
    reviews: 850,
    badge: "Kids Love",
    img: "images/cat_food.png",
    delivery: "In 25 min"
  },
  {
    id: 3009,
    name: "Chicken Fried Rice",
    category: "food",
    price: 219,
    originalPrice: 259,
    rating: 4.6,
    reviews: 950,
    badge: "Popular",
    img: "images/cat_food.png",
    delivery: "In 25 min"
  },
  {
    id: 3010,
    name: "Butter Chicken with Naan",
    category: "food",
    price: 349,
    originalPrice: 429,
    rating: 4.8,
    reviews: 1350,
    badge: "Combo",
    img: "images/cat_food.png",
    delivery: "In 30 min"
  }
];
